//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamTungSon_K22CNT1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pts_TACGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pts_TACGIA()
        {
            this.Pts_SACH = new HashSet<Pts_SACH>();
        }
    
        public string Pts_MaTG { get; set; }
        public string Pts_TenTacGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pts_SACH> Pts_SACH { get; set; }
    }
}
