//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhamTungSon_K22CNT1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pts_SACH
    {
        public string Pts_MaSach { get; set; }
        public string Pts_TenSach { get; set; }
        public Nullable<int> Pts_SoTrang { get; set; }
        public Nullable<int> Pts_NamXB { get; set; }
        public string Pts_MaTG { get; set; }
        public Nullable<bool> Pts_TrangThai { get; set; }
    
        public virtual Pts_TACGIA Pts_TACGIA { get; set; }
    }
}
